#!/usr/bin/env bash
set -Eeuo pipefail

# First-run setup wizard. Gathers the per-host values you would otherwise hand-edit
# — the Plausible host and the Caddy/Let's Encrypt email — generates the runtime
# secrets locally with openssl, and writes .env. No external vault: every secret
# here is a machine-generated random consumed only by this box.
#
# Re-runnable: existing secrets in .env are PRESERVED (re-running never rotates the
# Postgres password, which is bound to the initialized DB volume); only DOMAIN and
# CADDY_EMAIL are refreshed. Any prompt can be pre-answered by exporting
# DOMAIN / CADDY_EMAIL before running.
#
#   ./scripts/configure.sh
#   DOMAIN=stats.example.com CADDY_EMAIL=me@example.com ./scripts/configure.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${ROOT_DIR}/.env"

DEFAULT_DOMAIN="stats.yourdomain.example"

command -v openssl >/dev/null 2>&1 || { echo "openssl is required to generate secrets." >&2; exit 1; }

# ---- Gather values (env wins; else prompt; email is required) ----------------
if [[ -z "${DOMAIN:-}" ]]; then
  read -rp "Plausible host (e.g. stats.example.com) [${DEFAULT_DOMAIN}]: " DOMAIN
  DOMAIN="${DOMAIN:-$DEFAULT_DOMAIN}"
fi

if [[ -z "${CADDY_EMAIL:-}" ]]; then
  read -rp "Caddy / Let's Encrypt email: " CADDY_EMAIL
fi
[[ -n "${CADDY_EMAIL:-}" ]] || { echo "A Caddy / Let's Encrypt email is required." >&2; exit 1; }

# ---- Secrets: reuse any already in .env, else generate ------------------------
# Read a KEY's value from an existing .env (empty if the file or key is absent).
# cut -d= -f2- keeps everything after the first '=', so base64 padding ('=') in a
# value survives intact. Always returns 0 — a missing file/key is not an error, and
# under `set -e` a non-zero return here would abort the assignment that calls it.
existing() {
  [[ -f "$OUTPUT_FILE" ]] || return 0
  grep -E "^$1=" "$OUTPUT_FILE" 2>/dev/null | head -1 | cut -d= -f2- || true
}

SECRET_KEY_BASE="$(existing SECRET_KEY_BASE)"
TOTP_VAULT_KEY="$(existing TOTP_VAULT_KEY)"
POSTGRES_PASSWORD="$(existing POSTGRES_PASSWORD)"

# postgres password is hex (URL-safe): compose.yml interpolates it raw into
# DATABASE_URL, and base64's '/','+','=' break Ecto's URL parser. hex 32 = 256 bits.
secrets_state="reused existing"
if [[ -z "$SECRET_KEY_BASE" || -z "$TOTP_VAULT_KEY" || -z "$POSTGRES_PASSWORD" ]]; then
  secrets_state="generated"
  SECRET_KEY_BASE="${SECRET_KEY_BASE:-$(openssl rand -base64 48)}"
  TOTP_VAULT_KEY="${TOTP_VAULT_KEY:-$(openssl rand -base64 32)}"
  POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 32)}"
fi

# ---- Confirm before writing --------------------------------------------------
cat <<CONFIRM

About to configure with:
  Host (DOMAIN):   ${DOMAIN}
  Caddy email:     ${CADDY_EMAIL}
  Secrets:         ${secrets_state}

This writes ${OUTPUT_FILE} (mode 600). Existing secrets are preserved.
CONFIRM
read -rp "Proceed? [y/N]: " reply
[[ "${reply:-}" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }

# ---- Write .env --------------------------------------------------------------
umask 077
cat > "$OUTPUT_FILE" <<ENV
# Generated by scripts/configure.sh — real secrets, never commit (gitignored).

# ---- Plausible --------------------------------------------------------------
DOMAIN=${DOMAIN}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
TOTP_VAULT_KEY=${TOTP_VAULT_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DISABLE_REGISTRATION=true

# ---- Caddy (HTTP-01) --------------------------------------------------------
CADDY_EMAIL=${CADDY_EMAIL}
ENV
chmod 600 "$OUTPUT_FILE"

cat <<DONE

Wrote ${OUTPUT_FILE} (secrets ${secrets_state}). Next:
  - On the VPS: scripts/bootstrap-plausible-stack.sh, then scripts/deploy-services.sh
  - Smoke test: curl -I https://${DOMAIN}
DONE
